applications:
  - name: example
    trigger_id: xxxxxxxxxxxxxxxx
    source_owner: sakajunquality
    source_name: example-app
    manifest_owner: sakajunquality
    manifest_name: example-deployment
    manifest_base_branch: master
    image_tag: gcr.io/$PROJECT_ID/hoge
    manifests:
      - env: staging
        files:
          - overlays/staging/deployment.yaml
      - env: production
        files:
          - overlays/production/deployment.yaml

git_author:
  name: sakajunquality
  email: test@sakajunquality.dev

slack_notify_channel: "#deploy"
